### ISSUE TITLE
Changes in buttons in Score View

### ISSUE THREAD

**Issue by jpedrocm** [GTCMT/MusicEnsembleEdu#11]
I believe it would be a good idea to have the "Back" button at the bottom left of the view instead of top left. Also, I think the first first page of a score could have an invisible previous page button; the last page, then, would have an invisible next page button. Thoughts?

**Comment by alexanderlerch** [comment]
Not sure about whether the button should be bottom instead of top. What
is your reasoning for that?

I think it is enough if the next/back buttons are disabled for the
last/first page.

**Comment by jpedrocm** [comment]
I guess it would look better to have it aligned with the other two buttons in the bottom: recording and exporting buttons. It's a design change only.

**Comment by jpedrocm** [comment]
I've set them invisible. One wouldn't be able to tell the difference between enabled or not.
