### ISSUE TITLE
debug assertion: vector subscript out of range

### ISSUE THREAD

**Issue by alexanderlerch** [GTCMT/MusicEnsembleEdu#13]
Steps to reproduce (windows-10):

1. Select 1st exercise "au clair de lune"
2. Select Soprano
3. Press record
4. When the play cursor is finished with the first line, the debug assertion is thrown

**Comment by jpedrocm** [comment]
It also happened with me in Windows 8.1. Few others exercises also throw this error.

**Comment by jpedrocm** [comment]
Temporary fix added.

**Comment by alexanderlerch** [comment]
So do we consider this still an open bug of a fixed issue?
