### ISSUE TITLE
Wrong evaluation of rest and B notes

### ISSUE THREAD

**Issue by jpedrocm** [GTCMT/MusicEnsembleEdu#14]
Rest notes are being evaluated as incorrect every time, and B notes are often being evaluated as correct even when there's no sound. I still need to confirm this is not happening in my computer only.

**Comment by jpedrocm** [comment]
I manually adjusted the mic input level in my computer from 99 to 75, and these evaluation errors are not being reproduced anymore. We need to find a way of dealing with this in the code.

**Comment by alexanderlerch** [comment]
I would like to find out the reason first.

**Comment by jpedrocm** [comment]
The way the program works right now, any value in the pitch_array_hz will be evaluated as a rest only if this value is 0Hz. And the only way this value is set to 0Hz is if the RMS amplitude value of the window is not bigger than a constant threshold. With a higher mic input level, the windows of the audio buffer become louder, making each have a higher RMS value and thus, the array value won't be 0Hz. This should explain errors with rest assessment.

**Comment by alexanderlerch** [comment]
Right, I can understand that. Ideally we would want an calibration step
measuring the RMS of 'silence'.

That does not explain the B being correct, though?

Alexander

On 2016-06-08 14:26, João Pedro Magalhães wrote:
> The way the program works right now, any value in the pitch_array_hz
> will be evaluated as a rest only if this value is 0Hz. And the only way
> this value is set to 0Hz is if the RMS amplitude value of the window is
> not bigger than a constant threshold. With a higher mic input level, the
> windows of the audio buffer become louder, making each have a higher RMS
> value and thus, the array value won't be 0Hz. This should explain errors
> with rest assessment.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/GTCMT/MusicEnsembleEdu/issues/14#issuecomment-224683762>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFCzKlpz-Tbdt6ROgyKKLuNiCZoLw7Ckks5qJwlQgaJpZM4IvMKn>.
> 

-- 
Alexander Lerch

Assistant Professor, GT Center for Music Technology
www.gtcmt.gatech.edu

www.AudioContentAnalysis.org
www.musicinformatics.gatech.edu

**Comment by jpedrocm** [comment]
I believe not entirely. I checked the pitch_array_hz values, and when the mic input level is higher, there are a lot of 1002Hz values in it, which would be B5, incorrectly assessing other B's too because of the octave transposition. But this doesn't explain where these 1002Hz come from. I'm trying to figure that out.

**Comment by cplaguna-audio** [comment]
We wrap around octaves before checking pitch deviation in the evaluation.
It just so happens that with a reference of B, the deviation between 0 hz
and B gets mapped to zero. But I thought we fixed this already...

**Comment by cplaguna-audio** [comment]
(Sorry for not replying through GitHub)

**Comment by alexanderlerch** [comment]
[Actually you did reply through github, you just didn't know :) ]

That was my first thought, too, but we found it was just the max
frequency initialization that is returned when no local maxima are
found. We might want to consider only detecting maxima over a threshold
there later as well.

Alexander

On 2016-06-08 15:17, Christopher Laguna wrote:
> (Sorry for not replying through GitHub)
> 
> On Wednesday, June 8, 2016, Chris Laguna <cplaguna37@gmail.com> wrote:
> 
>> We wrap around octaves before checking pitch deviation in the evaluation.
>> It just so happens that with a reference of B, the deviation between 0 hz
>> and B gets mapped to zero. But I thought we fixed this already...
>>
>> On Wednesday, June 8, 2016, João Pedro Magalhães <notifications@github.com
>> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>>
>>> I believe not entirely. I checked the pitch_array_hz values, and when the
>>> mic input level is higher, there are a lot of 1002Hz values in it, which
>>> would be B5, incorrectly assessing other B's too because of the octave
>>> transposition. But this doesn't explain where these 1002Hz come from. I'm
>>> trying to figure that out.
>>>
>>> —
>>> You are receiving this because you are subscribed to this thread.
>>> Reply to this email directly, view it on GitHub
>>>
> <https://github.com/GTCMT/MusicEnsembleEdu/issues/14#issuecomment-224692593>,
>>> or mute the thread
>>>
> <https://github.com/notifications/unsubscribe/AJ8C-hAcnnfTUXN7rLm6nEKd6wdLkzaaks5qJxBXgaJpZM4IvMKn>
>>> .
>>>
>>
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/GTCMT/MusicEnsembleEdu/issues/14#issuecomment-224698342>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFCzKkmoUjratsq5dICocNxvPwnB-yabks5qJxVEgaJpZM4IvMKn>.
> 

-- 
Alexander Lerch

Assistant Professor, GT Center for Music Technology
www.gtcmt.gatech.edu

www.AudioContentAnalysis.org
www.musicinformatics.gatech.edu
