### ISSUE TITLE
Rename variables to project convention

### ISSUE THREAD

**Issue by jpedrocm** [GTCMT/MusicEnsembleEdu#16]
This is the general style recommendation found in the documentation:
­ - Class names are CamelCase
­ - Function names are camelCaseBeginningWithLowerCase
­ - Variable names are lower_with_underscores
­ - Member variables are _lower_with_underscore_at_beginning
­ - Const variables are ALL_UPPERCASE

What about const variables that are also member variables? And static member variables?

**Comment by alexanderlerch** [comment]
Let's not overthink this. But if you want to, you can add a
recommendation for const (Aren't static members always const anway?).

On 2016-06-09 10:44, João Pedro Magalhães wrote:
> This is the general style recommendation found in the documentation:
> ­ - Class names are CamelCase
> ­ - Function names are camelCaseBeginningWithLowerCase
> ­ - Variable names are lower_with_underscores
> ­ - Member variables are _lower_with_underscore_at_beginning
> ­ - Const variables are ALL_UPPERCASE
> 
> What about const variables that are also member variables? And static
> member variables?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/GTCMT/MusicEnsembleEdu/issues/16>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AFCzKkEfyWk4SZefd_Z9AdxfPDEWDQMcks5qKCbJgaJpZM4IyDQP>.
> 

-- 
Alexander Lerch

Assistant Professor, GT Center for Music Technology
www.gtcmt.gatech.edu

www.AudioContentAnalysis.org
www.musicinformatics.gatech.edu

**Comment by jpedrocm** [comment]
Static members are tied to the class, so its value is shared for every instance of that class. But this value can be changed.

**Comment by alexanderlerch** [comment]
My mistake, you are correct. That is a horrible idea. We DO NOT want a
style guide for static class members, as we DO NOT ALLOW this in our
code. At all! The thought makes me shudder.

On 2016-06-09 11:28, João Pedro Magalhães wrote:
> Static members are tied to the class, so its value is shared for every
> instance of that class. But this value can be changed.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/GTCMT/MusicEnsembleEdu/issues/16#issuecomment-224931881>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFCzKrTZ9OqYQsYmo6MizCg1SEKiFsf2ks5qKDEkgaJpZM4IyDQP>.
> 

-- 
Alexander Lerch

Assistant Professor, GT Center for Music Technology
www.gtcmt.gatech.edu

www.AudioContentAnalysis.org
www.musicinformatics.gatech.edu

**Comment by jpedrocm** [comment]
Alright. How about this order of priority?
1) Const member variables are _UPPERCASE_WITH_LEADING_UNDERSCORE
2) Member variables are _lowercase_with_leading_underscore
3) Const variables are ALL_UPPERCASE
4) Variable names are all_lowercase

**Comment by alexanderlerch** [comment]
I don't really like the all uppercase as these are preprocessor
statements in nearly all common style guides. What about something like
a trailing k?

On 2016-06-09 12:46, João Pedro Magalhães wrote:
> Alright. How about this order of priority?
> 1) Const member variables are _UPPERCASE_WITH_LEADING_UNDERSCORE
> 2) Member variables are _lowercase_with_leading_underscore
> 3) Const variables are ALL_UPPERCASE
> 4) Variable names are all_lowercase
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/GTCMT/MusicEnsembleEdu/issues/16#issuecomment-224955492>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFCzKrjXzXnZv9tZ8E9cyfB-MD8x5nWBks5qKENjgaJpZM4IyDQP>.
> 

-- 
Alexander Lerch

Assistant Professor, GT Center for Music Technology
www.gtcmt.gatech.edu

www.AudioContentAnalysis.org
www.musicinformatics.gatech.edu

**Comment by jpedrocm** [comment]
1) Const member variables are _kall_lowercase
2) Member variables are _lowercase_with_leading_underscore
3) Const variables are kall_lowercase
4) Variable names are all_lowercase

**Comment by cplaguna-audio** [comment]
Actually, why would you ever need constant member variables that were not
static?

I think they should either be static const or not-static not-const

**Comment by jpedrocm** [comment]
I can't think of a case too, but there are some not static const members in the code. I'm planning to change them later.

**Comment by alexanderlerch** [comment]
Yes, and why should you ever use static members that are not const?

Exactly our thoughts - static and const should go hand-in-hand for
members, that's why we decided not to have a definition in our style
guide for static, only for const :)

Alexander

On 2016-06-09 15:56, Christopher Laguna wrote:
> Actually, why would you ever need constant member variables that were not
> static?
> 
> I think they should either be static const or not-static not-const
> 
> On Thursday, June 9, 2016, João Pedro Magalhães <notifications@github.com>
> wrote:
> 
>> 1) Const member variables are _kall_lowercase
>> 2) Member variables are _lowercase_with_leading_underscore
>> 3) Const variables are kall_lowercase
>> 4) Variable names are all_lowercase
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>>
> <https://github.com/GTCMT/MusicEnsembleEdu/issues/16#issuecomment-224981675>,
>> or mute the thread
>>
> <https://github.com/notifications/unsubscribe/AJ8C-swmHAG_nfq8hY56Q0cjA8RuOz6uks5qKFjOgaJpZM4IyDQP>
>> .
>>
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/GTCMT/MusicEnsembleEdu/issues/16#issuecomment-225007858>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFCzKmoN3M3ynaHqQRQpTPcy4hL54Ow-ks5qKG_hgaJpZM4IyDQP>.
> 

-- 
Alexander Lerch

Assistant Professor, GT Center for Music Technology
www.gtcmt.gatech.edu

www.AudioContentAnalysis.org
www.musicinformatics.gatech.edu

**Comment by cplaguna-audio** [comment]
Joao, tell me where you saw those variables and I can see if they should be
changed.

**Comment by jpedrocm** [comment]
Sounds good. The headers were:
AudioEngine, PitchTracker, PlaybackSynth, RingBuffer, NoteAssessment, PagedOverlayComponent, MainWindow, LoadScoreView, LoadScoreController, ClassroomController, PagedScoreController.

**Comment by cplaguna-audio** [comment]
*AudioEngine, PitchTracker, PlaybackSynth, RingBuffer*
Apparently you are allowed to initialize constant member variables in the
constructor. These classes use static member variables like _kwindow_size
and _khop_size, which are set at alloc-time and meant to never change. I
think this is actually a fair use case. Let me know what you think.



*NoteAssessment, PagedOverlayComponent, MainWindow, LoadScoreView,
ClassroomController, PagedScoreController*These should all be static.

*LoadScoreController*
const Score* _kscore;
This is actually a (non-const) pointer to a const Score. Meaning the score
itself is read-only, but the pointer can change. So this is actually not a
const variable and should not have the 'k' prefix.

**Comment by jpedrocm** [comment]
For the first group, I can't see the advantage of keeping the variables only const.

I agree with everything else, though! Thank you.
