### ISSUE TITLE
memory leak in ACFPitchTracker

### ISSUE THREAD

**Issue by alexanderlerch** [GTCMT/MusicEnsembleEdu#9]
line 51: delete currentframe; is never called.

Also, two important remarks:
1. when you use malloc (why would you, BTW?), you have to use free, not delete!
2. we agreed on NO ALLOCATIONS IN THE PROCESS THREAD, right?

**Comment by jpedrocm** [comment]
The memory leak found is related to the musicxml library, and changes to the allocation were done.
